language: python

python:
  - "2.7"

env:
  - TOXENV=py27-django110
  - TOXENV=py27-django111
  - TOXENV=py37-django110
  - TOXENV=py37-django111

branches:
    only:
        - master

install: pip install --quiet tox

# command to run tests
script: tox

after_script:
    - if [ $TOXENV == "py27-django19" ]; then
        pip install --quiet coveralls;
        coveralls;
      fi

addons:
  apt:
    sources:
      - deadsnakes
    packages:
      - python3.7
